# Generated by Django 4.2.9 on 2024-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0003_user_email_user_login_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
