# Generated by Django 4.2.9 on 2024-02-02 15:16

import calapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[calapp.models.validate_ensc_mail]),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
