# Generated by Django 4.2.9 on 2024-02-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0006_musictheorylesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictheorylesson',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
