# Generated by Django 4.2.9 on 2024-03-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0008_musictheorylesson_lesson_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[('LOGO', 'Logo'), ('MISC', 'Miscellaneous')], default='MISC', max_length=8),
            preserve_default=False,
        ),
    ]
