# Generated by Django 4.2.9 on 2024-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0009_photo_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
