# Generated by Django 4.2.9 on 2024-03-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0010_remove_photo_owner_photo_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calapp.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calapp.user')),
            ],
        ),
    ]
